### PR TITLE
Add first_or_initialize and first! to RecordSet

### PR DESCRIPTION
**Pull request by ridiculous**
A couple AR like finder methods. How do you guys feel about this? If :+1: then I'll add some specs

### CODE REVIEW

**Comment by outoftime** [comment]
I'm down!

**Comment by ridiculous** [comment]
Cool! Also, is there currently a method equivalent to [this one](https://gist.github.com/ridiculous/ef620e93448e653d05dc#file-cequel_by_key-rb-L11) in the code base? I didn't see one ...

**Comment by outoftime** [comment]
@ridiculous the closest thing would be:

```ruby
Merchant[1]['facebook']['4213578641d']
```

but I get the impression people don't find the hash-like interface particularly intuitive, so I'm definitely open to what you're proposing.

Would love to merge this—would you have a chance to add some specs?

**Comment by ridiculous** [comment]
Oh cool, didn't know you could do that! I kinda like that, is that documented?

I'll add some specs this week.

**Comment by outoftime** [comment]
It's mentioned [here](https://github.com/cequel/cequel#record-sets), but I don't emphasize it in the README as my impression is that people don't find it terribly intuitive.

Looking forward to merging this one in!!

**Comment by outoftime** [comment]
@ridiculous any chance you could throw some specs on this?

**Comment by ridiculous** [comment]
Adding em now! Sorry for the delay. Did you want me to add [.by_key](https://gist.github.com/ridiculous/ef620e93448e653d05dc#file-cequel_by_key-rb-L11) as well?

**Comment by ridiculous** [comment]
Is there a reason the `Gemfile.lock` isn't checked in?

**Comment by ridiculous** [comment]
Specs added :tada:

**Comment by outoftime** [comment]
Thank you! (Sorry to go dark!)

**Pull request merged**
