### PR TITLE
add AR enum like support

### PR DESCRIPTION
**Pull request by phoet**
adding enum-like support:

```ruby
column :status, :enum, values: { open: 1, closed: 2 }
```

* will be handled as type `Int`
* calling `model.status` will return the symbol ie. `:open` or `:closed`
* expects setter to be called with symbol ie. `model.status(:open)`
* exposes helpers ie. `model.open?`
* exposes values-mapping on a class-level `ModelClass.status`

looking forward to your feedback

for reference: https://github.com/cequel/cequel/issues/351#issuecomment-271907539

### CODE REVIEW

**Comment by pezra** [comment]
👍

**Comment by phoet** [comment]
@pezra how should i go about documenting this feature? just in the readme or are there other places that should be updated?

**Comment by pezra** [comment]
I think the readme and in the method comments of`Properties.ClassMethods#column` would be great. Once that is done i will merge it.

**Comment by phoet** [comment]
@pezra i added some docs. please feel free to change it to your liking if there are any issues with it. also added a changelog entry.

**Comment by pezra** [comment]
This is ready to merge. I am waiting to update this branch so that i can get an older PR's tests to complete and get i merged. Hopefully i can merge this today and release a new version.

**Comment by phoet** [comment]
@pezra awesome thx!

**Comment by pezra** [comment]
released in 2.1.0

**Pull request merged**
