### PR TITLE
Add STATIC column support

### PR DESCRIPTION
**Pull request by ryanwilliams**
Allows you to have static columns when using a clustering key.

e.g.

    class Post
      include Cequel::Record

      key :blog_subdomain, :text
      key :id, :timeuuid, auto: true
      column :blog_title, :text, static: true
      column :title, :text
      column :body, :text
      column :created_at, :timestamp
    end

### CODE REVIEW

**Comment by pezra** [comment]
@ryanwilliams, i know the PR is old but if you are still interested in this (i know i am) please rebase it onto master. Once the tests pass i am willing to merge it.

**Comment by devdazed** [comment]
i am also very interested in this.

**Comment by pezra** [comment]
@devdazed, if you wanted to take this feature over that would be fine by me. Just make sure you reference this PR in the new one, if you do.

**Comment by outoftime** [comment]
Hi from retirement! I think it would be really cool to model static columns as a flavor of parent-child relationships. Basically the static columns comprise the “parent” model, and queries against the table act like a precooked `JOIN` query. Just a thought!

**Comment by outoftime** [comment]
(This could generalize to situations where a composite-keyed table has no static columns, but also does not have a corresponding “parent” table—in that case the parent model would just have a key and a `has_many` association)

**Comment by pezra** [comment]
Hmm... @outoftime, are you suggesting something like:
```
class Child
  # ...
  belongs_to :parent, denormalize: [:column_x_from_parent, :column_y_from_parent]
```
Which would result in `parent_column_x` and `parent_column_y` static columns on `Child`. Querying `Child` would return model instances that always had a `parent` instance that was partially loaded with the parent id, column_x and column_y values from the child table?

That is in a interesting idea, though it sounds like quite a bit of work.

**Comment by outoftime** [comment]
@pezra what I had in mind was a little different:

```ruby
class Parent
  include Cequel::Record::Static

  key :subdomain, :string
  column :column_x, :string
  column :column_y, :string
end

class Child
  include Cequel::Record

  belongs_to :parent
  key :id, :uuid
  column :column_z, :string
end
```

These two classes would together model a single underlying table, where the partition key is `subdomain`; the clustering column is `id`; `column_x` and `column_y` are static columns; and `column_z` is a normal column.

**Comment by pezra** [comment]
That is better than what i imagined you where suggesting. :smile: I like it. I'd be ok with the more simplistic approach of this PR too, though.

**Comment by pezra** [comment]
@ryanwilliams, @devdazed, et al, i am closing this PR due to inactivity. Please reopen if you can devote some time to completing this work.

**Pull request closed without merging**
