### PR TITLE
Support Rails 5 #310

### PR DESCRIPTION
**Pull request by emn178**
rebase and pull request again.

### CODE REVIEW

**Comment by pezra** [comment]
please add <https://github.com/cequel/cequel/commit/dddc095a029743ac7eeedd82e9faf1680e5de14c> to your pr.

**Comment by pezra** [comment]
also, use the [build matrix exclusion](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix) feature to not run the tests on the combination of rails 5 & ruby 2.1

**Comment by emn178** [comment]
I have already added this
https://github.com/cequel/cequel/pull/322/files#diff-354f30a63fb0907d4ad57269548329e3R33

it seems not working.

**Comment by pezra** [comment]
Merged. Thanks for the improvement!

**Pull request merged**
