### PR TITLE
Add synchronization around use of @cluster and other variables Fix #332

### LINKED ISSUE #332: NameError: instance variable @cluster not defined
Judging from the if statement, this must be the result of a race condition. We're running Cequel in sidekiq when this happens

Stack trace of the frames that are in the `cequel` gem

```
/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 252:in `remove_instance_variable'
…/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 252:in `clear_active_connections!'
…/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 318:in `rescue in client_retry'
…/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 313:in `client_retry'
…/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 214:in `block in execute_with_options'
…cequel-6b652daac361/lib/cequel/metal/
request_logger.rb:  33:in `block in log'
…cequel-6b652daac361/lib/cequel/metal/
request_logger.rb:  33:in `log'
…/gems/cequel-6b652daac361/lib/cequel/metal/
keyspace.rb: 213:in `execute_with_options'
…ler/gems/cequel-6b652daac361/lib/cequel/metal/
batch.rb:  67:in `apply'
…/cequel-6b652daac361/lib/cequel/metal/
batch_manager.rb:  52:in `block in batch'
…/cequel-6b652daac361/lib/cequel/metal/
batch_manager.rb:  52:in `tap'
…/cequel-6b652daac361/lib/cequel/metal/
batch_manager.rb:  52:in `batch'
…ems/cequel-6b652daac361/lib/cequel/record/
callbacks.rb:  34:in `save'
…s/cequel-6b652daac361/lib/cequel/record/
validations.rb:  53:in `save'
…er/gems/cequel-6b652daac361/lib/cequel/record/
dirty.rb:  48:in `save'
…s/cequel-6b652daac361/lib/cequel/record/
persistence.rb:  47:in `block in create'
…s/cequel-6b652daac361/lib/cequel/record/
persistence.rb:  47:in `tap'
…s/cequel-6b652daac361/lib/cequel/record/
persistence.rb:  47:in `create'
…reams/.rbenv/versions/2.3.0/lib/ruby/2.3.0/
delegate.rb:  83:in `method_missing'
…ms/cequel-6b652daac361/lib/cequel/record/
record_set.rb: 930:in `block in method_missing'
…r/gems/cequel-6b652daac361/lib/cequel/record/
scoped.rb:  34:in `with_scope'
…ms/cequel-6b652daac361/lib/cequel/record/
record_set.rb: 930:in `method_missing'
…reams/.rbenv/versions/2.3.0/lib/ruby/2.3.0/
delegate.rb:  83:in `method_missing'
```

### PR DESCRIPTION
**Pull request by hydrogen18**
This class has the correct primitives to be thread safe, but it was missing a `synchronize` block.
Fix #332

### CODE REVIEW

**Comment by pezra** [comment]
Please rebase and i'll merge this.

**Comment by hydrogen18** [comment]
This has no conflicts now.

**Comment by pezra** [comment]
Thanks for the improvement.

**Comment by bernardofire** [comment]
Hi @pezra, @hydrogen18. 
Could you guys, explain I I'm getting this error and what does it mean?:
screen shot 2016-12-05 at 16 15 06

**Comment by pezra** [comment]
@bernardofire, that is pretty interesting. Given the `if defined? @cluster` guard it implies that multiple threads are running this method at the same time. Cequel is *not* thread safe, though we are working in that direction. Are you running this in a multi-threaded setup?

**Comment by lxbrito** [comment]
Hi @pezra,
@bernardofire asked me to answer you. Yes, definitely. We are running some instances of Sidekiq with 12 threads each.  Do you think that doubling the sidekiq instances while halving the thread count would make us see less @cluster errors?

**Comment by pezra** [comment]
I suspect you would see less of that issue with more processes and fewer threads.

Another option would be to submit a PR to convert that variable into a thread variable or synchronize access to that variable. I would love to get Cequel fully thread safe. If you choose this route I will do everything i can to support your effort.

**Comment by hydrogen18** [comment]
@lxbrito @bernardofire You're using 2.0.2 which does not contain the fix for this issue, upgrade to 2.0.3

**Comment by lxbrito** [comment]
@hydrogen18 Do you mean git master? I couldn't find 2.0.3 release.

**Comment by pezra** [comment]
I haven't released 2.0.3 yet. I am getting a couple more tiny PRs. It should be out today.

**Comment by pezra** [comment]
Released in 2.0.3. Thanks, again, for the improvement.

**Pull request merged**
